language: erlang
otp_release:
  - 18.1
install:
  - make
  - ./rebar3 update
script:
  - make check
notifications:
  email: christopher.meiklejohn@gmail.com
  slack: lasp-lang:hiPRNnbUa3zdGrrXZfGRAF7D
  irc: "irc.freenode.org#lasp-lang"
sudo: required
